/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditIndexRouteImport } from './routes/edit/index'
import { Route as EditWishlistIdIndexRouteImport } from './routes/edit/$wishlistId/index'
import { Route as EditWishlistIdWeaponHashRouteImport } from './routes/edit/$wishlistId/weapon/$hash'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditIndexRoute = EditIndexRouteImport.update({
  id: '/edit/',
  path: '/edit/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditWishlistIdIndexRoute = EditWishlistIdIndexRouteImport.update({
  id: '/edit/$wishlistId/',
  path: '/edit/$wishlistId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditWishlistIdWeaponHashRoute =
  EditWishlistIdWeaponHashRouteImport.update({
    id: '/edit/$wishlistId/weapon/$hash',
    path: '/edit/$wishlistId/weapon/$hash',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edit': typeof EditIndexRoute
  '/edit/$wishlistId': typeof EditWishlistIdIndexRoute
  '/edit/$wishlistId/weapon/$hash': typeof EditWishlistIdWeaponHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edit': typeof EditIndexRoute
  '/edit/$wishlistId': typeof EditWishlistIdIndexRoute
  '/edit/$wishlistId/weapon/$hash': typeof EditWishlistIdWeaponHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/edit/': typeof EditIndexRoute
  '/edit/$wishlistId/': typeof EditWishlistIdIndexRoute
  '/edit/$wishlistId/weapon/$hash': typeof EditWishlistIdWeaponHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/edit'
    | '/edit/$wishlistId'
    | '/edit/$wishlistId/weapon/$hash'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/edit' | '/edit/$wishlistId' | '/edit/$wishlistId/weapon/$hash'
  id:
    | '__root__'
    | '/'
    | '/edit/'
    | '/edit/$wishlistId/'
    | '/edit/$wishlistId/weapon/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditIndexRoute: typeof EditIndexRoute
  EditWishlistIdIndexRoute: typeof EditWishlistIdIndexRoute
  EditWishlistIdWeaponHashRoute: typeof EditWishlistIdWeaponHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/': {
      id: '/edit/'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$wishlistId/': {
      id: '/edit/$wishlistId/'
      path: '/edit/$wishlistId'
      fullPath: '/edit/$wishlistId'
      preLoaderRoute: typeof EditWishlistIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$wishlistId/weapon/$hash': {
      id: '/edit/$wishlistId/weapon/$hash'
      path: '/edit/$wishlistId/weapon/$hash'
      fullPath: '/edit/$wishlistId/weapon/$hash'
      preLoaderRoute: typeof EditWishlistIdWeaponHashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditIndexRoute: EditIndexRoute,
  EditWishlistIdIndexRoute: EditWishlistIdIndexRoute,
  EditWishlistIdWeaponHashRoute: EditWishlistIdWeaponHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
